[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# Disable the standard library
[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1

[profile.dev]
opt-level = "z"
lto = true
panic = "abort"